name: my first workflow
on:
  push:
    branches:
      - main
jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: print welcome massage
        run: echo " welcome the first workflow pipeline "
      - name: Checkout scm
        uses: actions/checkout@v7

  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: crate a folder sayed
        run: mkdir sayed
      - name: touch file in the folder sayed
        run: echo "sayedatwh">> sayed/file1
      - name: cat file1
        run: cat sayed/file1

  third-job: 
    runs-on: ubuntu-latest
    steps:
      - name: print home directory
        run: ls -la